CREATE TABLE sys_user (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(64) NOT NULL,
    password_hash VARCHAR2(100) NOT NULL,
    display_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(120),
    phone VARCHAR2(32),
    status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    department_id NUMBER(19),
    token_version NUMBER(10) DEFAULT 0 NOT NULL,
    last_login_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uk_sys_user_username UNIQUE (username),
    CONSTRAINT ck_sys_user_status CHECK (status IN ('ACTIVE', 'DISABLED'))
);

CREATE TABLE sys_role (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code VARCHAR2(64) NOT NULL,
    role_name VARCHAR2(100) NOT NULL,
    data_scope VARCHAR2(30) DEFAULT 'SELF' NOT NULL,
    status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    sort_order NUMBER(10) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uk_sys_role_code UNIQUE (role_code),
    CONSTRAINT ck_sys_role_status CHECK (status IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT ck_sys_role_data_scope CHECK (data_scope IN ('ALL', 'DEPARTMENT', 'SELF'))
);

CREATE TABLE sys_permission (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_code VARCHAR2(100) NOT NULL,
    permission_name VARCHAR2(120) NOT NULL,
    module VARCHAR2(50) NOT NULL,
    description VARCHAR2(255),
    status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uk_sys_permission_code UNIQUE (permission_code),
    CONSTRAINT ck_sys_permission_status CHECK (status IN ('ACTIVE', 'DISABLED'))
);

CREATE TABLE sys_menu (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id NUMBER(19),
    menu_code VARCHAR2(80) NOT NULL,
    menu_name VARCHAR2(100) NOT NULL,
    route_path VARCHAR2(200) NOT NULL,
    component VARCHAR2(200),
    permission_code VARCHAR2(100),
    icon VARCHAR2(80),
    sort_order NUMBER(10) DEFAULT 0 NOT NULL,
    visible NUMBER(1) DEFAULT 1 NOT NULL,
    status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uk_sys_menu_code UNIQUE (menu_code),
    CONSTRAINT ck_sys_menu_visible CHECK (visible IN (0, 1)),
    CONSTRAINT ck_sys_menu_status CHECK (status IN ('ACTIVE', 'DISABLED'))
);

CREATE TABLE sys_user_role (
    user_id NUMBER(19) NOT NULL,
    role_id NUMBER(19) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_sys_user_role PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_sys_user_role_user FOREIGN KEY (user_id) REFERENCES sys_user(id),
    CONSTRAINT fk_sys_user_role_role FOREIGN KEY (role_id) REFERENCES sys_role(id)
);

CREATE TABLE sys_role_permission (
    role_id NUMBER(19) NOT NULL,
    permission_id NUMBER(19) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_sys_role_permission PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_sys_role_permission_role FOREIGN KEY (role_id) REFERENCES sys_role(id),
    CONSTRAINT fk_sys_role_permission_permission FOREIGN KEY (permission_id) REFERENCES sys_permission(id)
);

CREATE TABLE audit_log (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id NUMBER(19),
    actor_username VARCHAR2(64),
    action VARCHAR2(80) NOT NULL,
    target_type VARCHAR2(80) NOT NULL,
    target_id VARCHAR2(80),
    result VARCHAR2(20) NOT NULL,
    message VARCHAR2(500),
    ip_address VARCHAR2(64),
    user_agent VARCHAR2(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_audit_log_result CHECK (result IN ('SUCCESS', 'FAILURE', 'DENIED'))
);

CREATE INDEX idx_sys_user_role_user ON sys_user_role (user_id);
CREATE INDEX idx_sys_user_role_role ON sys_user_role (role_id);
CREATE INDEX idx_sys_role_permission_role ON sys_role_permission (role_id);
CREATE INDEX idx_sys_role_permission_permission ON sys_role_permission (permission_id);
CREATE INDEX idx_audit_log_actor ON audit_log (actor_user_id, created_at);

INSERT INTO sys_role (id, role_code, role_name, data_scope, sort_order) VALUES (1, 'SUPER_ADMIN', '超级管理员', 'ALL', 1);
INSERT INTO sys_role (id, role_code, role_name, data_scope, sort_order) VALUES (2, 'ADMIN', '管理员', 'ALL', 2);
INSERT INTO sys_role (id, role_code, role_name, data_scope, sort_order) VALUES (3, 'AGENT', '坐席或工程师', 'SELF', 3);
INSERT INTO sys_role (id, role_code, role_name, data_scope, sort_order) VALUES (4, 'USER', '普通用户', 'SELF', 4);

INSERT INTO sys_permission (id, permission_code, permission_name, module, description) VALUES (1, 'system:user:manage', '管理用户', 'system', '管理用户账号');
INSERT INTO sys_permission (id, permission_code, permission_name, module, description) VALUES (2, 'system:role:manage', '管理角色和权限', 'system', '管理角色、权限和授权关系');
INSERT INTO sys_permission (id, permission_code, permission_name, module, description) VALUES (3, 'system:menu:view', '查看菜单', 'system', '查看前端菜单摘要');
INSERT INTO sys_permission (id, permission_code, permission_name, module, description) VALUES (4, 'knowledge:document:upload', '上传知识库文档', 'knowledge', '上传企业知识库文档');
INSERT INTO sys_permission (id, permission_code, permission_name, module, description) VALUES (5, 'knowledge:document:manage', '管理知识库文档', 'knowledge', '管理知识库文档和解析状态');
INSERT INTO sys_permission (id, permission_code, permission_name, module, description) VALUES (6, 'knowledge:document:view', '查看知识库内容', 'knowledge', '查看启用的知识库内容');
INSERT INTO sys_permission (id, permission_code, permission_name, module, description) VALUES (7, 'ai:chat:ask', '发起 AI 问答', 'ai', '提交 AI 问答请求');
INSERT INTO sys_permission (id, permission_code, permission_name, module, description) VALUES (8, 'ai:chat:history:view', '查看本人问答历史', 'ai', '查看本人的 AI 问答历史');
INSERT INTO sys_permission (id, permission_code, permission_name, module, description) VALUES (9, 'ticket:create', '创建工单', 'ticket', '从问答或手动入口创建工单');
INSERT INTO sys_permission (id, permission_code, permission_name, module, description) VALUES (10, 'ticket:view:own', '查看本人工单', 'ticket', '查看本人提交或分配给自己的工单');
INSERT INTO sys_permission (id, permission_code, permission_name, module, description) VALUES (11, 'ticket:assign', '分配工单', 'ticket', '分配待处理工单');
INSERT INTO sys_permission (id, permission_code, permission_name, module, description) VALUES (12, 'ticket:process', '处理工单', 'ticket', '坐席处理工单');
INSERT INTO sys_permission (id, permission_code, permission_name, module, description) VALUES (13, 'ticket:manage', '管理工单', 'ticket', '管理全部工单');
INSERT INTO sys_permission (id, permission_code, permission_name, module, description) VALUES (14, 'dashboard:view', '查看统计看板', 'dashboard', '查看基础统计看板');

INSERT INTO sys_menu (id, menu_code, menu_name, route_path, component, permission_code, icon, sort_order) VALUES (1, 'chat', 'AI 问答', '/app/ai/chat', 'views/ai/chat', 'ai:chat:ask', 'MessageCircle', 1);
INSERT INTO sys_menu (id, menu_code, menu_name, route_path, component, permission_code, icon, sort_order) VALUES (2, 'tickets', '我的工单', '/app/tickets/my', 'views/tickets/my', 'ticket:view:own', 'Ticket', 2);
INSERT INTO sys_menu (id, menu_code, menu_name, route_path, component, permission_code, icon, sort_order) VALUES (3, 'agent-workbench', '坐席工作台', '/app/tickets/assigned', 'views/tickets/assigned', 'ticket:process', 'Briefcase', 3);
INSERT INTO sys_menu (id, menu_code, menu_name, route_path, component, permission_code, icon, sort_order) VALUES (4, 'knowledge', '知识库管理', '/app/knowledge', 'views/knowledge', 'knowledge:document:manage', 'Folder', 4);
INSERT INTO sys_menu (id, menu_code, menu_name, route_path, component, permission_code, icon, sort_order) VALUES (5, 'users', '用户权限管理', '/app/system', 'views/system', 'system:user:manage', 'Users', 5);
INSERT INTO sys_menu (id, menu_code, menu_name, route_path, component, permission_code, icon, sort_order) VALUES (6, 'dashboard', '统计看板', '/app/admin/dashboard', 'views/admin/dashboard', 'dashboard:view', 'ChartColumn', 6);

INSERT INTO sys_user (id, username, password_hash, display_name, status, token_version) VALUES (1, 'superadmin', '$2a$10$8wEayODt4hidF3affYdSaOy1Zl2N2R.zfyPUIAS8Xce9Llb.817Vm', '超级管理员', 'ACTIVE', 0);
INSERT INTO sys_user (id, username, password_hash, display_name, status, token_version) VALUES (2, 'admin', '$2a$10$8wEayODt4hidF3affYdSaOy1Zl2N2R.zfyPUIAS8Xce9Llb.817Vm', '系统管理员', 'ACTIVE', 0);
INSERT INTO sys_user (id, username, password_hash, display_name, status, token_version) VALUES (3, 'agent', '$2a$10$8wEayODt4hidF3affYdSaOy1Zl2N2R.zfyPUIAS8Xce9Llb.817Vm', '演示坐席', 'ACTIVE', 0);
INSERT INTO sys_user (id, username, password_hash, display_name, status, token_version) VALUES (4, 'user', '$2a$10$8wEayODt4hidF3affYdSaOy1Zl2N2R.zfyPUIAS8Xce9Llb.817Vm', '演示用户', 'ACTIVE', 0);

INSERT INTO sys_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO sys_user_role (user_id, role_id) VALUES (2, 2);
INSERT INTO sys_user_role (user_id, role_id) VALUES (3, 3);
INSERT INTO sys_user_role (user_id, role_id) VALUES (4, 4);

INSERT INTO sys_role_permission (role_id, permission_id)
SELECT 1, id FROM sys_permission;

INSERT INTO sys_role_permission (role_id, permission_id)
SELECT 2, id FROM sys_permission
WHERE permission_code IN (
    'system:user:manage',
    'system:role:manage',
    'system:menu:view',
    'knowledge:document:upload',
    'knowledge:document:manage',
    'knowledge:document:view',
    'ticket:assign',
    'ticket:manage',
    'dashboard:view'
);

INSERT INTO sys_role_permission (role_id, permission_id)
SELECT 3, id FROM sys_permission
WHERE permission_code IN (
    'knowledge:document:view',
    'ticket:view:own',
    'ticket:process'
);

INSERT INTO sys_role_permission (role_id, permission_id)
SELECT 4, id FROM sys_permission
WHERE permission_code IN (
    'ai:chat:ask',
    'ai:chat:history:view',
    'ticket:create',
    'ticket:view:own'
);
